name: publish master branch

on:
  push:
    branches:
      - src

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 30     # all jobs
    steps:
      #timeout-minutes: 20  # each step
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          extended: true

      - name: Build
        run: hugo --minify --baseUrl=${{ secrets.HOST }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
